import { writable } from 'svelte/store';
export const mapConfig = writable({
  "title": "How common are drug-related crimes in the EU?",
  "subtitle": "In 2023, around 1.18 million EU citizens were involved in illegal drug-related activities involving precursors.",
  "colourSchemeClasses": 7,
  "data": "country,id,value,extraInfo,text_content,link_text,link_url_target,audio_url_1,audio_url_2,audio_url_3,image_url_source,image_url_target,video_url\nAustria,AT,392.51,true,Total number: 35737,,,,,,,,\nBelgium,BE,501.71,true,Total number: 58915,,,,,,,,\nBulgaria,BG,88.26,true,Total number: 5691,,,,,,,,\nCyprus,CY,115.27,true,Total number: 1094,,,,,,,,\nCzechia,CZ,39.97,true,Total number: 4328,,,,,,,,\nGermany,DE,417.33,true,Total number: 346877,,,,,,,,\nDenmark,DK,504.56,true,Total number: 29934,,,,,,,,\nEstonia,EE,241.38,true,Total number: 3297,,,,,,,,\nGreece,EL,122.08,true,Total number: 12713,,,,,,,,\nSpain,ES,43.74,true,Total number: 21033,,,,,,,,\nFinland,FI,481.38,true,Total number: 26784,,,,,,,,\nFrance,FR,507.76,true,Total number: 346628,,,,,,,\nCroatia,HR,268.92,true,Total number: 10356,,,,,,,,\nHungary,HU,68.64,true,Total number: 6589,,,,,,,,\nIreland,IE,316.79,true,Total number: 16699,,,,,,,,\nItaly,IT,51.47,true,Total number: 30365,,,,,,,,\nLithuania,LT,133.38,true,Total number: 3811,,,,,,,,\nLuxembourg,LU,473.51,true,Total number: 3129,,,,,,,,\nLatvia,LV,71.69,true,Total number: 1350,,,,,,,,\nMalta,MT,36.90,true,Total number: 200,,,,,,,,\nNetherlands,NL,76.24,true,Total number: 13580,,,,,,,,\nPoland,PL,183.24,true,Total number: 67346,,,,,,,,\nPortugal,PT,72.85,true,Total number: 7661,,,,,,,,\nRomania,RO,67.04,true,Total number: 12775,,,,,,,,\nSweden,SE,1094.55,true,Total number: 115164,,,,,,,,\nSlovenia,SI,61.13,true,Total number: 1294,,,,,,,,\nSlovakia,SK,25.07,true,Total number: 1361,,,,,,,,",
  "parsedData": [
    {
      "country": "Austria",
      "id": "AT",
      "value": 392.51,
      "extraInfo": true,
      "text_content": "Total number: 35737",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Belgium",
      "id": "BE",
      "value": 501.71,
      "extraInfo": true,
      "text_content": "Total number: 58915",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Bulgaria",
      "id": "BG",
      "value": 88.26,
      "extraInfo": true,
      "text_content": "Total number: 5691",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Cyprus",
      "id": "CY",
      "value": 115.27,
      "extraInfo": true,
      "text_content": "Total number: 1094",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Czechia",
      "id": "CZ",
      "value": 39.97,
      "extraInfo": true,
      "text_content": "Total number: 4328",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Germany",
      "id": "DE",
      "value": 417.33,
      "extraInfo": true,
      "text_content": "Total number: 346877",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Denmark",
      "id": "DK",
      "value": 504.56,
      "extraInfo": true,
      "text_content": "Total number: 29934",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Estonia",
      "id": "EE",
      "value": 241.38,
      "extraInfo": true,
      "text_content": "Total number: 3297",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Greece",
      "id": "EL",
      "value": 122.08,
      "extraInfo": true,
      "text_content": "Total number: 12713",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Spain",
      "id": "ES",
      "value": 43.74,
      "extraInfo": true,
      "text_content": "Total number: 21033",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Finland",
      "id": "FI",
      "value": 481.38,
      "extraInfo": true,
      "text_content": "Total number: 26784",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "France",
      "id": "FR",
      "value": 507.76,
      "extraInfo": true,
      "text_content": "Total number: 346628",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Croatia",
      "id": "HR",
      "value": 268.92,
      "extraInfo": true,
      "text_content": "Total number: 10356",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Hungary",
      "id": "HU",
      "value": 68.64,
      "extraInfo": true,
      "text_content": "Total number: 6589",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Ireland",
      "id": "IE",
      "value": 316.79,
      "extraInfo": true,
      "text_content": "Total number: 16699",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Italy",
      "id": "IT",
      "value": 51.47,
      "extraInfo": true,
      "text_content": "Total number: 30365",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Lithuania",
      "id": "LT",
      "value": 133.38,
      "extraInfo": true,
      "text_content": "Total number: 3811",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Luxembourg",
      "id": "LU",
      "value": 473.51,
      "extraInfo": true,
      "text_content": "Total number: 3129",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Latvia",
      "id": "LV",
      "value": 71.69,
      "extraInfo": true,
      "text_content": "Total number: 1350",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Malta",
      "id": "MT",
      "value": 36.9,
      "extraInfo": true,
      "text_content": "Total number: 200",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Netherlands",
      "id": "NL",
      "value": 76.24,
      "extraInfo": true,
      "text_content": "Total number: 13580",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Poland",
      "id": "PL",
      "value": 183.24,
      "extraInfo": true,
      "text_content": "Total number: 67346",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Portugal",
      "id": "PT",
      "value": 72.85,
      "extraInfo": true,
      "text_content": "Total number: 7661",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Romania",
      "id": "RO",
      "value": 67.04,
      "extraInfo": true,
      "text_content": "Total number: 12775",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Sweden",
      "id": "SE",
      "value": 1094.55,
      "extraInfo": true,
      "text_content": "Total number: 115164",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovenia",
      "id": "SI",
      "value": 61.13,
      "extraInfo": true,
      "text_content": "Total number: 1294",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovakia",
      "id": "SK",
      "value": 25.07,
      "extraInfo": true,
      "text_content": "Total number: 1361",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    }
  ],
  "datasetType": "values",
  "datasetUnit": "fullNumbers",
  "percentRounded": false,
  "colourSchemeType": "sequential",
  "colourScheme": "red",
  "colourSchemeReverse": false,
  "headlineAvailable": true,
  "subheadlineAvailable": true,
  "tooltipAvailable": true,
  "scaleBarAvailable": true,
  "overrideScaleValues": true,
  "legendAvailable": true,
  "textSourceAvailable": true,
  "textSourceDescription": "Source",
  "textSource": "Eurostat (2023)",
  "textNoteAvailable": true,
  "textNoteDescription": "Note",
  "textNote": "Total number of police-recorded offences of unlawful acts involving controlled drugs or precursors. Reports of offences against national drug legislation (use, possession, trafficking, etc.) reflect differences in law but also the different ways in which the law is enforced and applied, and the priorities and resources allocated to specific problems by criminal justice agencies.",
  "textDataAccessAvailable": true,
  "linkDataAccessDescription": "Access the data",
  "linkDataAccess": "https://ec.europa.eu/eurostat/databrowser/view/crim_off_cat__custom_18895231/default/table",
  "legend1": "No data available",
  "legend1Color": "#E0E0E0",
  "colorBarFirstValue": "25",
  "colorBarLastValue": "1100",
  "customUnitLabelAvailable": true,
  "customUnitLabel": "per hundred thousand inhabitants",
  "tooltipExtraInfoLabel": "Click here",
  "translate": {
    "title": "How common are drug-related crimes in the EU?",
    "subtitle": "In 2023, around 1.18 million EU citizens were involved in illegal drug-related activities involving precursors.",
    "textNoteDescription": "Note",
    "textNote": "Total number of police-recorded offences of unlawful acts involving controlled drugs or precursors. Reports of offences against national drug legislation (use, possession, trafficking, etc.) reflect differences in law but also the different ways in which the law is enforced and applied, and the priorities and resources allocated to specific problems by criminal justice agencies.",
    "textSourceDescription": "Source",
    "textSource": "Eurostat (2023)",
    "linkDataAccessDescription": "Access the data",
    "legend1": "No data available",
    "tooltipExtraInfoLabel": "Click here",
    "extraInfo_AT": "Total number: 35737",
    "extraInfo_BE": "Total number: 58915",
    "extraInfo_BG": "Total number: 5691",
    "extraInfo_CY": "Total number: 1094",
    "extraInfo_CZ": "Total number: 4328",
    "extraInfo_DE": "Total number: 346877",
    "extraInfo_DK": "Total number: 29934",
    "extraInfo_EE": "Total number: 3297",
    "extraInfo_EL": "Total number: 12713",
    "extraInfo_ES": "Total number: 21033",
    "extraInfo_FI": "Total number: 26784",
    "extraInfo_FR": "Total number: 346628",
    "extraInfo_HR": "Total number: 10356",
    "extraInfo_HU": "Total number: 6589",
    "extraInfo_IE": "Total number: 16699",
    "extraInfo_IT": "Total number: 30365",
    "extraInfo_LT": "Total number: 3811",
    "extraInfo_LU": "Total number: 3129",
    "extraInfo_LV": "Total number: 1350",
    "extraInfo_MT": "Total number: 200",
    "extraInfo_NL": "Total number: 13580",
    "extraInfo_PL": "Total number: 67346",
    "extraInfo_PT": "Total number: 7661",
    "extraInfo_RO": "Total number: 12775",
    "extraInfo_SE": "Total number: 115164",
    "extraInfo_SI": "Total number: 1294",
    "extraInfo_SK": "Total number: 1361"
  },
  "clusters": [],
  "colorScale": null,
  "extraInfo_AT": "Total number: 35737",
  "extraInfo_BE": "Total number: 58915",
  "extraInfo_BG": "Total number: 5691",
  "extraInfo_CY": "Total number: 1094",
  "extraInfo_CZ": "Total number: 4328",
  "extraInfo_DE": "Total number: 346877",
  "extraInfo_DK": "Total number: 29934",
  "extraInfo_EE": "Total number: 3297",
  "extraInfo_EL": "Total number: 12713",
  "extraInfo_ES": "Total number: 21033",
  "extraInfo_FI": "Total number: 26784",
  "extraInfo_FR": "Total number: 346628",
  "extraInfo_HR": "Total number: 10356",
  "extraInfo_HU": "Total number: 6589",
  "extraInfo_IE": "Total number: 16699",
  "extraInfo_IT": "Total number: 30365",
  "extraInfo_LT": "Total number: 3811",
  "extraInfo_LU": "Total number: 3129",
  "extraInfo_LV": "Total number: 1350",
  "extraInfo_MT": "Total number: 200",
  "extraInfo_NL": "Total number: 13580",
  "extraInfo_PL": "Total number: 67346",
  "extraInfo_PT": "Total number: 7661",
  "extraInfo_RO": "Total number: 12775",
  "extraInfo_SE": "Total number: 115164",
  "extraInfo_SI": "Total number: 1294",
  "extraInfo_SK": "Total number: 1361"
});